#!/usr/bin/env python3
"""
ps2classic - autobuild script
Compiles the ps2classic tool for the current platform.
Supports Linux, macOS, Windows (MSYS2/MinGW), ARM, Termux.
"""

import os
import sys
import shutil
import platform
import subprocess
import glob as glob_mod

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BINARY_NAME = "ps2classic"
BINARY_OUT = os.path.join(SCRIPT_DIR, BINARY_NAME)

SYSTEM = platform.system().lower()
MACHINE = platform.machine().lower()


def print_step(msg):
    print(f"\n==> {msg}")


def run(cmd, cwd=None, fatal=True):
    print(f"  + {' '.join(cmd) if isinstance(cmd, list) else cmd}")
    res = subprocess.run(cmd, cwd=cwd or SCRIPT_DIR)
    if fatal and res.returncode != 0:
        print(f"FAILED: {cmd}", file=sys.stderr)
        sys.exit(1)
    return res


def detect_platform():
    """Returns a platform tag: linux, termux, macos, windows, msys2, freebsd"""
    if "termux" in os.environ.get("PREFIX", ""):
        return "termux"
    if os.environ.get("ANDROID_ROOT") and os.path.exists("/system/bin"):
        return "termux"
    if SYSTEM == "windows" or "msys" in os.environ.get("MSYSTEM", "").lower():
        return "windows"
    if SYSTEM == "darwin":
        return "macos"
    if SYSTEM == "linux":
        return "linux"
    if SYSTEM == "freebsd":
        return "freebsd"
    return "unknown"


def detect_pkg_manager():
    """Detect available package manager."""
    for pm in [
        ("apt-get", "apt-get"),
        ("pkg", "pkg"),
        ("pacman", "pacman"),
        ("apk", "apk"),
        ("yum", "yum"),
        ("dnf", "dnf"),
        ("brew", "brew"),
        ("port", "port"),
    ]:
        if shutil.which(pm[1]):
            return pm[0]
    return None


def has_sudo():
    if os.name == "nt":
        return False
    if shutil.which("doas"):
        return True
    try:
        subprocess.run(
            ["sudo", "-n", "true"],
            capture_output=True,
            timeout=5,
        )
        return True
    except (subprocess.SubprocessError, FileNotFoundError):
        return False


def install_dependencies(plat):
    if os.name == "nt" or plat == "windows":
        print("  [skip] dependencies: assume MSYS2/MinGW already has gcc")
        return

    needed = []
    if not shutil.which("gcc") and not shutil.which("cc") and not shutil.which("clang"):
        needed.extend(["gcc", "build-essential"] if shutil.which("apt-get") else ["gcc"])

    if plat == "termux":
        needed = ["binutils", "build-essential", "clang"]

    if not needed:
        print("  [ok] gcc/clang already installed")
        return

    pm = detect_pkg_manager()
    if not pm:
        print("  [warn] no package manager found, skipping dep install")
        return

    sudo = has_sudo()
    prefix = []
    if sudo:
        prefix = ["sudo"]
    elif os.geteuid() != 0:
        print("  [warn] no sudo, trying without root")

    cmds = {
        "apt-get": [["apt-get", "update"], ["apt-get", "install", "-y"] + needed],
        "pkg": [["pkg", "install", "-y"] + needed],
        "pacman": [["pacman", "-S", "--noconfirm"] + needed],
        "apk": [["apk", "add"] + needed],
        "yum": [["yum", "install", "-y"] + needed],
        "dnf": [["dnf", "install", "-y"] + needed],
        "brew": [["brew", "install"] + [x for x in needed if x != "build-essential"]],
    }

    if sudo:
        if pm in cmds:
            for cmd in cmds[pm]:
                run(prefix + cmd)
    else:
        for cmd in cmds[pm]:
            run(cmd)


def write_custom_makefile(plat):
    """Write a Makefile tailored to the current platform."""
    common_objs = ["tools.o", "aes.o", "sha1.o", "iso.o"]
    cflags = "-g -O3 -W -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64"

    if plat == "windows":
        common_objs.append("mingw_mmap.o")
        cflags += ' -D__MSVCRT__ -D__USE_MINGW_FSEEK'

    cc = "gcc"
    if plat == "termux":
        if shutil.which("cc"):
            cc = "cc"
        elif shutil.which("clang"):
            cc = "clang"

    if plat == "macos":
        if shutil.which("clang"):
            cc = "clang"

    license_text = (
        "/* DO NOT EDIT - auto-generated by build.py */\n"
    )

    with open(os.path.join(SCRIPT_DIR, "Makefile.autogen"), "w") as f:
        f.write(f"""# Auto-generated Makefile for {plat}
# DO NOT EDIT - regenerated by build.py

TOOLS\t= ps2classic
COMMON\t= {" ".join(common_objs)}
DEPS\t= Makefile.autogen tools.h types.h

CC\t= {cc}
CFLAGS\t= {cflags}
LDFLAGS\t=

OBJS\t= $(COMMON) $(addsuffix .o, $(TOOLS))

all: $(TOOLS)

$(TOOLS): %: %.o $(COMMON) $(DEPS)
\t$(CC) $(CFLAGS) -o $@ $< $(COMMON) $(LDFLAGS)

$(OBJS): %.o: %.c $(DEPS)
\t$(CC) $(CFLAGS) -c -o $@ $<

clean:
\t-rm -f $(OBJS) $(TOOLS)

distclean: clean
\t-rm -f Makefile.autogen
""")
    return "Makefile.autogen"


def build(plat):
    makefile = write_custom_makefile(plat)

    print_step("Cleaning previous build")
    run(["make", "-f", makefile, "clean"])

    print_step("Compiling ps2classic")
    run(["make", "-f", makefile, "-j", str(os.cpu_count() or 2)])

    binary = os.path.join(SCRIPT_DIR, BINARY_NAME)
    if os.path.exists(binary):
        size = os.path.getsize(binary)
        print(f"\n  Binary: {binary}")
        print(f"  Size:   {size:,} bytes")
        print(f"  Plat:   {plat} / {MACHINE}")
        print(f"  Arch:   {'64-bit' if sys.maxsize > 2**32 else '32-bit'}")
        return True
    else:
        print("ERROR: binary not found after build!", file=sys.stderr)
        return False


def clean_old_artifacts():
    for f in [
        "Makefile.autogen",
        "*.o",
        BINARY_NAME,
        BINARY_NAME + ".exe",
    ]:
        for match in glob_mod.glob(os.path.join(SCRIPT_DIR, f)):
            try:
                os.remove(match)
            except OSError:
                pass


def main():
    print("=" * 54)
    print("  ps2classic autobuild")
    print("=" * 54)

    plat = detect_platform()
    print(f"\nPlatform: {plat}")
    print(f"System:   {SYSTEM}")
    print(f"Machine:  {MACHINE}")
    print(f"Python:   {sys.version}")

    if shutil.which("gcc"):
        ver = subprocess.run(
            ["gcc", "--version"], capture_output=True, text=True
        ).stdout.split("\n")[0]
        print(f"Compiler: {ver}")
    elif shutil.which("clang"):
        ver = subprocess.run(
            ["clang", "--version"], capture_output=True, text=True
        ).stdout.split("\n")[0]
        print(f"Compiler: {ver}")
    elif shutil.which("cc"):
        print("Compiler: cc (generic)")

    print_step("Installing dependencies")
    install_dependencies(plat)

    if not shutil.which("gcc") and not shutil.which("cc") and not shutil.which("clang"):
        print("FATAL: no C compiler found. Install gcc/clang and try again.", file=sys.stderr)
        sys.exit(1)

    success = build(plat)

    if success:
        print("\n=== BUILD SUCCESS ===")
        print(f"Run: {BINARY_OUT}")
    else:
        print("\n=== BUILD FAILED ===", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
